//this file is autogenerated
export interface IService{
	info: IServiceInfo;
	servers: Array<IServer>;
}
export interface IServiceInfo{
	version: string;
	title: string;
	description?: string;
}
export interface IServer{
	url: string;
	description?: string;
	variables?: Map<String, any>;
};
export interface IMothershipService{
	info: IServiceInfo;
	servers: Array<IServer>;
}


export default class MothershipService implements IMothershipService{
	public info: IServiceInfo;
	public servers: Array<IServer>;
	constructor(){
		this.info =  {version: '1.0.0', title: 'Mothership',  };
		this.servers = [ 
		{  url: 'http://mothership-516381200.eu-west-1.elb.amazonaws.com', description: 'staging environment' },
	 ];
		console.log(this.info.title,' ready');
	}
	/* METHODS */
}


const service = new MothershipService();
