openapi: "3.0.0"
info:
  version: 1.0.0
  title: Mothership
servers:
  - url: http://mothership-516381200.eu-west-1.elb.amazonaws.com
    description: staging environment
paths:
  /api/resources/newsletter/subscription:
    post:
      summary: Create a subscription
      description: Creates customer newsletter subscription.
      operationId: createSubscription
      tags:
        - newsletter subscription
      responses:
        '200':
          description: newsletter subscription created
      requestBody:
        description: Provide customer email here
        content:
          'application/json':
            schema:
              $ref: '#/components/schemas/NewsletterSubscription'


components:
  schemas:
    ProductPreview:
      type: object
      properties:
        id:
          type: string
          description: you can use this id to perform product operations
          example: 9as8dfhasikfdjhasfiodu
        title:
          type: string
          example: Matte Revolution
        subtitle:
          type: string
          example: Very Victoria
        description:
          type: string
          example: 'Luminous, modern matte lipstick with a long-lasting hydrating formula to give you fuller, softer lips.'
        price:
          type: string
          example: '£32.00'
        sellLine:
          type: string
          example: 'New In'
        href:
          type: string
          example: "#"
        image:
          $ref: '#/components/schemas/Image'
        rollOverImage:
          $ref: '#/components/schemas/Image'
        availability:
          type: string
          enum:
            - BUNDLE
            - OUT_OF_STOCK
            - COMING_SOON
            - SOLD_OUT
            - AVAILABLE
        wishList:
          type: boolean
      title: ProductPreview

    Image:
      type: object
      properties:
        alt:
          type: string
          example: Image alt text
        imageSrc:
          type: string
          example: /placeholder/navigation/glow.png
        title:
          type: string
          example: Image Title
      title: Image

    ProductDetailsModel:
      type: object
      properties:
        breadcrumbs:
          type: array
          items:
            $ref: '#/components/schemas/Link'
        productName:
          type: string
        skus:
          type: array
          items:
            $ref: '#/components/schemas/Sku'
      title: ProductDetailsModel

    Link:
      type: object
      properties:
        href:
          type: string
          example: '#'
        label:
          type: string
          example: link label
      title: Link

    Sku:
      type: object
      properties:
        id:
          type: string
          description: you can use this id to perform product operations
          example: 9as8dfhasikfdjhasfiodu
        href:
          type: string
          example: '#'
        subtitle:
          type: string
          example: Very Victoria
        shortDescription:
          type: string
          example: 'Luminous, modern matte lipstick with a long-lasting hydrating formula to give you fuller, softer lips.'
        sellLine:
          type: string
          example: 'Award Winner'
        price:
          $ref: '#/components/schemas/PriceContainer'
      title: Sku

    PriceContainer:
      type: object
      description: "Previous price is optional, present in case of promotion"
      required:
        - current
      properties:
        current:
          $ref: '#/components/schemas/Price'
        previous:
          $ref: '#/components/schemas/Price'
      title: PriceContainer

    Price:
      required:
        - amount
        - currencyCode
      properties:
        amount:
          type: number
          example: 10.00
        currencyCode:
          type: string
          enum: [GBP, EUR]
          example: GBP